### ISSUE TITLE
image frame 1672371570248219967 dropped due to queue overflow

### ISSUE THREAD

**Issue by ZhangLiang-Cencen** [berndpfrommer/basalt_ros1#11]
hello,
when I run "roslaunch realsense2_camera rs_t265.launch" and roslaunch basalt_ros1 vio_t265.launch,
the screen printed "image frame 1672371570248219967 dropped due to queue overflow"

what can I do to solve this problem?

Thanks!

**Comment by ZhangLiang-Cencen** [comment]
ubuntu 18 dose not have this problem.

**Comment by ZhangLiang-Cencen** [comment]
I have try the method  "<arg name="enable_sync"           default="true"/>", but it does not work in ubuntu 20.

**Comment by ZhangLiang-Cencen** [comment]
I have try the method "  <arg name="enable_sync"           default="true"/>
 ", but it does not work in ubuntu 20.

**Comment by ZhangLiang-Cencen** [comment]
The method "<arg name ="enable_sync"            default="true" >" dose not work in ubuntu 20

**Comment by ZhangLiang-Cencen** [comment]
The method`  <arg name="enable_sync"           default="true"/>` does not work in ubuntu 20

**Comment by berndpfrommer** [comment]
queue overflow is often due to slow CPU.
Regarding the option "enable_sync": What launch file are you referring to?

**Comment by ZhangLiang-Cencen** [comment]
> queue overflow is often due to slow CPU. Regarding the option "enable_sync": What launch file are you referring to?

rs_t265.launch

**Comment by ZhangLiang-Cencen** [comment]
Could you please tell me how to solve the problem of slow CPU?

**Comment by berndpfrommer** [comment]
I cannot find the "rs_t265.launch" file in the source tree. Could you please provide a link to it?
About the slow CPU problem: first find out if it even is due to high CPU load. Run "top" while you are getting the error messages and see what processes are consuming the most CPU cycles.

**Comment by ZhangLiang-Cencen** [comment]
Thanks for your help!
If you run the following code, you will find the "rs_t265.launch".
```
mkdir -p ~/realsense_ws/src

cd ~/realsense_ws/src/

git clone https://github.com/IntelRealSense/realsense-ros.git

cd realsense-ros/

git checkout `git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1` //检查分支是否为最新
```

**Comment by ZhangLiang-Cencen** [comment]
I also want to ask another question.
When I run this algorithm outdoor, the position_z  was inaccurate.
![Screenshot from 2023-01-06 12-55-52](https://user-images.githubusercontent.com/54580468/210932918-f7c623ae-22c6-4006-a6d4-4a62e7b19ba4.png)

**Comment by berndpfrommer** [comment]
Please understand that I cannot provide support for the realsense t265 as I don't own such a device.
As for your last question about z-axis inaccuracy: you are giving me no context at all, which makes it impossible to provide any reasonable response.
