### ISSUE TITLE
how to launch only visual odometry without IMU? 

### ISSUE THREAD

**Issue by ergys00** [berndpfrommer/basalt_ros1#14]
hi there how can i launch only the visual odometry basalt reather than the visual inertial odometry one that is launched by the vio.launch file?

**Comment by berndpfrommer** [comment]
This is currently not possible. You can try hacking it by changing the last argument [here](https://github.com/berndpfrommer/basalt_ros1/blob/master/src/vio_backend.cpp) to "false". No idea if it'll work.
```
// create VIO object
  vio_ = basalt::VioEstimatorFactory::getVioEstimator(
      config, calib, basalt::constants::g, true);
```
