### ISSUE TITLE
Does BASALT work with stereo cameras like ZED2 ?

### ISSUE THREAD

**Issue by Aishkrish18** [berndpfrommer/basalt_ros1#15]
Is basalt specific to only fisheye cameras or can it be used with stereo cameras? If yes where do i change the parameters after i Calibrate the cameras ?

**Comment by berndpfrommer** [comment]
Basalt can be used both with fisheye (equidistant projection) or regular lenses (radial-tangential distortion model). Please read the basalt source code on how to do this. You can find the relevant example config files in the "config" directory of this repo.
Alas, this repo is for ROS1 and will no longer be supported going forward. I will mark it correspondingly.
