### ISSUE TITLE
Basalt package error

### ISSUE THREAD

**Issue by zainmehdi** [berndpfrommer/basalt_ros1#2]
Hi, 
I am trying to install this ros package following the instruction you mentioned but it keeps giving me basalt pkfconfig error

 Could not find a package configuration file provided by "basalt" with any
  of the following names:

    basaltConfig.cmake
    basalt-config.cmake
I have installed deb package for basalt. Is there a specific package thats missing ?

thanks

**Comment by berndpfrommer** [comment]
the basalt package is provided by the root basalt_ros repository. you need
to uninstall the basalt debian package, then follow the instructions here:
https://github.com/berndpfrommer/basalt_ros

**Comment by zainmehdi** [comment]
Thanks alot it worked.

**Comment by berndpfrommer** [comment]
I updated the build instructions so they point to the basalt_ros repo for build instructions,
