### ISSUE TITLE
update to latest version of basalt

### ISSUE THREAD

**Issue by berndpfrommer** [berndpfrommer/basalt_ros1#8]
update the wrapper to use the latest version of basalt.
See issue #7

**Comment by martinakos** [comment]
Basalt has released code for ICCV'21 paper "Square Root Marginalization for Sliding-Window Bundle Adjustment" in their master branch. This makes their code 36% faster while not losing any accuracy.  https://vision.in.tum.de/research/vslam/rootvo
It would be great to have your ros wrapper updated to this recent version of basalt.

**Comment by berndpfrommer** [comment]
I took a stab at it in June but gave up in frustration after more than a day. The problems lie somewhere between my limited understanding of catkin/ament/cmake and Basalt's use of source-level versions of third party libraries.

**Comment by berndpfrommer** [comment]
Eventually I've managed to get it working, but only on ROS2, and I won't back port to ROS1.
The new repo is in the "fresh start" branch here:
https://github.com/berndpfrommer/basalt_ros

**Comment by martinakos** [comment]
I actually prefer to use the old basalt now, as it's faster. See this unanswered question about performance: https://gitlab.com/VladyslavUsenko/basalt/-/issues/90
